# -*- coding: utf-8 -*-
"""PalmerPenguins.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15pnX3_-z8VxqhBXShLcaPAq7RuYFQJsr
"""

print("Introducing the Palmer Penguins:")
print("\tChinstrap!")
print("\tGentoo!")
print("and last but not least...")
print("\tAdelie!")
print("There are a total of 3 penguin species in this dataset.")